### ISSUE TITLE
Code Organization: Packaging

### ISSUE THREAD

**Issue by OmarRammah** [CSC207-2023Y-UofT/course-project-hrmanagement#43]
TA Comment: "Code organisation is pretty haphazard. It seems like the packages are as per the functionalities, but there is UI package at the root. Even there is another UI package within Payroll. Team needs to fix their app refactoring. Also, please remove the started code files since they are not part of your project."

Packaging needs to be fixed. Packaging should probably be done by use case, which means all files in the UI package needs to be separated into its appropriate functionality.

**Comment by sarahhe25** [comment]
redid packaging:
Our packaging structure is by individual features, and within them, the files for each feature is organized into clean architecture layers. 
For example, in the Payroll package, the files are organized into Entity, Use Case, UI, and DAO layers
In Time off, the files are organized into Entities, Use Case, GUI, and Data Access layers
For the employee/manager login / sign-in feature that all the other features depend on, it is organized as per CA layers. For instance, employee signUp and login info are contained in UI, Controller, Database, UseCase and Entities layer.
