### ISSUE TITLE
Clean Architecture with Packages

### ISSUE THREAD

**Issue by OmarRammah** [CSC207-2023Y-UofT/course-project-hrmanagement#44]
TA comment: "There are multiple violations of CA and the project structure is not well defined at all. Only payroll feature seems to have adhered to CA."

Within packages, CA structure needs to be followed. For reference, payroll structure is something like this:
- Usecase
- UI
- Entity
- Database
Files within the package should be divided roughly like this.

**Comment by sarahhe25** [comment]
Fixed packaging
Our packaging structure is by individual features, and within them, the files for each feature is organized into clean architecture layers. 
For example, in the Payroll package, the files are organized into Entity, Use Case, UI, and DAO layers
In Time off, the files are organized into Entities, Use Case, GUI, and Data Access layers
For the employee/manager login / sign-in feature that all the other features depend on, it is organized as per CA layers. For instance, employee signUp and login info are contained in UI, Controller, Database, UseCase and Entities layer.
We removed starter code file from the project
